require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BibleVersesController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # BibleVerse. As you add validations to BibleVerse, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BibleVersesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all bible_verses as @bible_verses" do
      bible_verse = BibleVerse.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:bible_verses)).to eq([bible_verse])
    end
  end

  describe "GET show" do
    it "assigns the requested bible_verse as @bible_verse" do
      bible_verse = BibleVerse.create! valid_attributes
      get :show, {:id => bible_verse.to_param}, valid_session
      expect(assigns(:bible_verse)).to eq(bible_verse)
    end
  end

  describe "GET new" do
    it "assigns a new bible_verse as @bible_verse" do
      get :new, {}, valid_session
      expect(assigns(:bible_verse)).to be_a_new(BibleVerse)
    end
  end

  describe "GET edit" do
    it "assigns the requested bible_verse as @bible_verse" do
      bible_verse = BibleVerse.create! valid_attributes
      get :edit, {:id => bible_verse.to_param}, valid_session
      expect(assigns(:bible_verse)).to eq(bible_verse)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BibleVerse" do
        expect {
          post :create, {:bible_verse => valid_attributes}, valid_session
        }.to change(BibleVerse, :count).by(1)
      end

      it "assigns a newly created bible_verse as @bible_verse" do
        post :create, {:bible_verse => valid_attributes}, valid_session
        expect(assigns(:bible_verse)).to be_a(BibleVerse)
        expect(assigns(:bible_verse)).to be_persisted
      end

      it "redirects to the created bible_verse" do
        post :create, {:bible_verse => valid_attributes}, valid_session
        expect(response).to redirect_to(BibleVerse.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bible_verse as @bible_verse" do
        post :create, {:bible_verse => invalid_attributes}, valid_session
        expect(assigns(:bible_verse)).to be_a_new(BibleVerse)
      end

      it "re-renders the 'new' template" do
        post :create, {:bible_verse => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested bible_verse" do
        bible_verse = BibleVerse.create! valid_attributes
        put :update, {:id => bible_verse.to_param, :bible_verse => new_attributes}, valid_session
        bible_verse.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested bible_verse as @bible_verse" do
        bible_verse = BibleVerse.create! valid_attributes
        put :update, {:id => bible_verse.to_param, :bible_verse => valid_attributes}, valid_session
        expect(assigns(:bible_verse)).to eq(bible_verse)
      end

      it "redirects to the bible_verse" do
        bible_verse = BibleVerse.create! valid_attributes
        put :update, {:id => bible_verse.to_param, :bible_verse => valid_attributes}, valid_session
        expect(response).to redirect_to(bible_verse)
      end
    end

    describe "with invalid params" do
      it "assigns the bible_verse as @bible_verse" do
        bible_verse = BibleVerse.create! valid_attributes
        put :update, {:id => bible_verse.to_param, :bible_verse => invalid_attributes}, valid_session
        expect(assigns(:bible_verse)).to eq(bible_verse)
      end

      it "re-renders the 'edit' template" do
        bible_verse = BibleVerse.create! valid_attributes
        put :update, {:id => bible_verse.to_param, :bible_verse => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bible_verse" do
      bible_verse = BibleVerse.create! valid_attributes
      expect {
        delete :destroy, {:id => bible_verse.to_param}, valid_session
      }.to change(BibleVerse, :count).by(-1)
    end

    it "redirects to the bible_verses list" do
      bible_verse = BibleVerse.create! valid_attributes
      delete :destroy, {:id => bible_verse.to_param}, valid_session
      expect(response).to redirect_to(bible_verses_url)
    end
  end

end
